alphatalk:
  ingest:
    poll-delay: 5m
    poll-initial-delay: 5s
    feeds:
      - id: yna-economy
        source: yna
        url: https://www.yna.co.kr/rss/economy.xml
      - id: hankyung-economy
        source: hankyung
        url: https://www.hankyung.com/feed/economy
      - id: mk-stock
        source: mk
        url: https://www.mk.co.kr/rss/50200011/
