[versions]
kotlin = "2.2.21"
spring-boot = "3.5.16"
spring-dependency-management = "1.1.7"
jackson = "2.19.0"
jjwt = "0.12.7"
rome = "2.1.0"
jsoup = "1.18.3"
ulid = "5.2.3"
liquibase = "4.31.1"
testcontainers = "1.21.4"
postgresql = "42.7.11"
resilience4j = "2.3.0"
java-websocket = "1.6.0"

[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
rome = { module = "com.rometools:rome", version.ref = "rome" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
ulid-creator = { module = "com.github.f4b6a3:ulid-creator", version.ref = "ulid" }
liquibase-core = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
resilience4j-ratelimiter = { module = "io.github.resilience4j:resilience4j-ratelimiter", version.ref = "resilience4j" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
